- name: Update packages on Ubuntu host
  hosts: all
  become: true
  become_user: root
  gather_facts: false

    tasks:
        - name: Update package cache
            apt:
                update_cache: yes

        - name: Upgrade packages
            apt:
                upgrade: dist
                autoremove: yes
                autoclean: yes
