---
- name: Update packages on Ubuntu hosts
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
