---
- name: Update and upgrade apt packages
  hosts: all 
  tasks:
    - name: Update packages with apt
      apt:
        update_cache: yes
      become: true
        
    - name: Upgrade packages with apt
      apt:
        upgrade: dist
      become: true
